# Generated by Django 5.0.8 on 2024-09-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_usersubscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='strip_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
